os: linux

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2

env:
  - SCALA_PROFILE="scala_2.11"
#  - SCALA_PROFILE="scala_2.12"

install:
  - chmod +x ./dev/test.sh
  - chmod +x ./dev/deploy-snapshot.sh
  - chmod +x ./dev/deploy-release.sh
  - docker-compose -f ./dev/docker-compose.yml up -d

script:
  - ./dev/test.sh

after_success:
  - curl -s https://codecov.io/bash | bash;

deploy:
  - provider: script
    edge: true
    cleanup: false
    script: ./dev/deploy-snapshot.sh
    on:
      branch: master

  - provider: script
    edge: true
    cleanup: false
    script: ./dev/deploy-release.sh
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^SETL-[0-9]+.[0-9]+.[0-9]+?$
