os: linux

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2

env:
  - MVN_OPT="--batch-mode clean:clean scoverage:report"

install:
  - export AWS_ACCESS_KEY_ID="fakeAccess"
  - export AWS_SECRET_ACCESS_KEY="fakeSecret"
  - export AWS_REGION="eu-west-1"
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker-compose -f ./dev/docker-compose.yml up -d

script:
  - mvn ${MVN_OPT}

after_script:
  - curl -s https://codecov.io/bash | bash
