os: linux

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2

env:
  - SCALA_VER="2.11" SPARK_VER="2.4" UPLOAD_COVERAGE="true"
  - SCALA_VER="2.12" SPARK_VER="2.4"
  - SCALA_VER="2.11" SPARK_VER="2.3"
  - SCALA_VER="2.12" SPARK_VER="2.3"

before_install:
  - chmod +x ./dev/test.sh
  - chmod +x ./dev/deploy-snapshot.sh
  - chmod +x ./dev/deploy-release.sh
  - chmod +x ./dev/change-scala-version.sh
  - ./dev/change-scala-version.sh ${SCALA_VER}

install:
  - docker-compose -f ./dev/docker-compose.yml up -d

script:
  - ./dev/test.sh

after_success:
  - |
    if [[ "$UPLOAD_COVERAGE" == "true" ]]; then
      echo upload code coverage report;
      curl -s https://codecov.io/bash | bash;
    fi

deploy:
  - provider: script
    skip_cleanup: true
    script: ./dev/deploy-snapshot.sh
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: ./dev/deploy-release.sh
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^SETL-[0-9]+.[0-9]+.[0-9]+?$
