os: linux

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2

env:
  - MVN_OPT="--batch-mode -ntp clean:clean scoverage:report"

install:
  - chmod +x ./dev/test.sh
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -ntp -B -V
  - docker-compose -f ./dev/docker-compose.yml up -d

script:
  - ./dev/test.sh

after_script:
  - curl -s https://codecov.io/bash | bash
