os: linux

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2

branches:
  only:
    - master

env:
  - MVN_OPT="--batch-mode clean:clean scoverage:report" AWS_ACCESS_KEY_ID="fakeAccess" AWS_SECRET_ACCESS_KEY="fakeSecret" AWS_REGION="eu-west-1"

install:
  - echo start install
  - mvn ${MAV_OPT} install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker-compose -f ./dev/docker-compose.yml up -d

script:
  - echo start build
  - docker container ls
  - mvn ${MVN_OPT}

after_script:
  - curl -s https://codecov.io/bash | bash
  - echo Build completed on `date`
