os: linux

language: java

jdk:
  - openjdk8

services:
  - docker

cache:
  directories:
    - ${HOME}/.m2

env:
  - MVN_OPT="--batch-mode clean:clean scoverage:report" AWS_ACCESS_KEY_ID="fakeAccess" AWS_SECRET_ACCESS_KEY="fakeSecret" AWS_REGION="eu-west-1"

stages:
  - test
  - deploy

#  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

#script:
#  - echo start build
#  - docker container ls
#  - mvn ${MVN_OPT}

jobs:
  include:
    - stage: test
      install:
        - echo install test
        #  - docker-compose -f ./dev/docker-compose.yml up -d
      script:
        - echo Test stage
        - cat hahaha
    - stage: deploy
      if: branch = master AND type = push
      install:
#        - echo ${MVN_SETTINGS} > ${TRAVIS_HOME}/.m2/settings.xml;
#        - echo ${MVN_SECURITY} > ${TRAVIS_HOME}/.m2/settings-security.xml;
        - echo install snapshot
      script:
        - echo deploy snapshot
    - stage: deploy
      if: tag =~ /^v.*$/ AND type = push
      install:
        - echo install release
      script:
        - echo deploy release

after_script:
  - |  # Upload the report only if triggered by a PR # curl -s https://codecov.io/bash | bash
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
      echo No coverage report will be uploaded
    else
      echo Publish report
    fi
  - echo Build completed on `date`
