version: 0.2

env:
  variables:
    AWS_ACCESS_KEY_ID: fakeAccess
    AWS_SECRET_ACCESS_KEY: fakeSecret
    AWS_REGION: eu-west-1
    MVN_OPT: --batch-mode clean:clean scoverage:report scala:doc
    DEPLOY: "false"

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
    commands:
      - gpg --list-keys
      - if [ "$DEPLOY" = "true" ]; then echo ${MVN_SETTINGS} > /root/.m2/settings.xml; fi
      - if [ "$DEPLOY" = "true" ]; then echo ${MVN_SECURITY} > /root/.m2/settings-security.xml; fi
      - if [ "$DEPLOY" = "true" ]; then echo ${GPG_KEY} | base64 -d > /root/ossrh_gpg.key; fi
      - if [ "$DEPLOY" = "true" ]; then gpg --import /root/ossrh_gpg.key; fi
  pre_build:
    commands:
      - echo starting services
      - docker version
      - docker-compose -f ./dev/docker-compose.yml up -d
  build:
    commands:
      - docker container ls
      - mvn ${MVN_OPT}
  post_build:
    commands:
      - echo Build completed on `date`

reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports