version: 0.2

env:
  variables:
    MVN_TEST_OPT: --batch-mode clean:clean test scala:doc
    MVN_DEPLOY_OPT: --batch-mode deploy -DskipTests
    MVN_PROFILE: -Pprovided
    DEPLOY: "false"

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
    commands:
      - |
        if [[ "$DEPLOY" != "false" ]]; then
           echo ${MVN_SETTINGS} > /root/.m2/settings.xml;
           echo ${MVN_SECURITY} > /root/.m2/settings-security.xml;
           echo ${GPG_KEY} | base64 -d | gpg --import;
        fi
  pre_build:
    commands:
      # variables for unit test
      - export AWS_ACCESS_KEY_ID="fakeAccess"
      - export AWS_SECRET_ACCESS_KEY="fakeSecret"
      - export AWS_REGION="eu-west-1"
      # launch services
      - docker-compose -f ./dev/docker-compose.yml up -d
  build:
    commands:
      - mvn ${MVN_TEST_OPT}
  post_build:
    commands:
      - |
        if [[ "$DEPLOY" = "RELEASE" ]]; then
           export MVN_PROFILE="-Prelease";
        fi
      - |
        if [[ "$DEPLOY" != "false" ]]; then
           echo Deploy to the $DEPLOY repository;
           mvn ${MVN_DEPLOY_OPT} ${MVN_PROFILE};
        else
           echo No deployment;
        fi

artifacts:
  files:
    - '**/*'
  base-directory: 'target/site'

reports:
  SurefireReports: # CodeBuild will create a report group called "SurefireReports".
    files: #Store all of the files
      - '**/*'
    base-directory: 'target/surefire-reports' # Location of the reports
