version: 0.2

env:
  variables:
    AWS_ACCESS_KEY_ID: fakeAccess
    AWS_SECRET_ACCESS_KEY: fakeSecret
    AWS_REGION: eu-west-1

phases:
  install:
    runtime-versions:
      java: corretto8
      docker: 18
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - docker version
      - docker-compose -f ./dev/docker-compose.yml up -d
      - sleep 30s
  build:
    commands:
      - ./mvnw clean test
  post_build:
    commands:
      - echo Build completed on `date`
