name: release

on:
  release:
    types: [published]

jobs:
  release_deployment:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - SCALA_VER: "2.12"
            SPARK_VER: "3.2"
          - SCALA_VER: "2.11"
            SPARK_VER: "2.4"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Before all
        run: |
          chmod +x ./dev/change-scala-version.sh
          ./dev/change-scala-version.sh ${{ matrix.SCALA_VER }}
          docker-compose -f ./dev/docker-compose.yml up -d

      - name: Prepare maven
        env:
          MVN_SETTINGS: ${{ secrets.MVN_SETTINGS }}
          MVN_SECURITY: ${{ secrets.MVN_SECURITY_SETTINGS }}
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "$MVN_SETTINGS" | base64 -d > "$HOME"/.m2/settings.xml
          echo "$MVN_SECURITY" | base64 -d > "$HOME"/.m2/settings-security.xml
          echo "$GPG_KEY" | base64 -d | gpg --import --batch > /dev/null 2>&1

      - name: Run tests
        run: |
          set -e
          export AWS_ACCESS_KEY_ID="fakeAccess"
          export AWS_SECRET_ACCESS_KEY="fakeSecret"
          export AWS_REGION="eu-west-1"
          mvn -B -ntp clean:clean scoverage:report -P snapshot,spark_${{ matrix.SPARK_VER }}

      # If the tag follows the format SETL-X.Y.Z-RC*, then release the RC version
      - name: RC version deployment
        if: ${{ startsWith( github.ref, 'refs/tags/SETL-' ) && contains( github.ref, '-RC' ) }}
        run: |
          RC_VER=-$(echo ${{ github.ref }} | cut -d'-' -f 3)
          mvn clean deploy scala:doc -ntp -B -DskipTests -P release,spark_${{ matrix.SPARK_VER }} -Dchangelist=$RC_VER

      # If the tag follows the format SETL-X.Y.Z, then release the stable version
      - name: Deployment
        if: ${{ startsWith( github.ref, 'refs/tags/SETL-' ) && !contains( github.ref, '-RC' ) }}
        run: mvn clean deploy scala:doc -ntp -B -DskipTests -P release,spark_${{ matrix.SPARK_VER }}
